name: Frontend Continuous Integration

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './starter/frontend/package-lock.json'
          
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ./starter/frontend/node_modules
            *!node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './starter/frontend/package-lock.json'
          
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ./starter/frontend/node_modules
            *!node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: CI=true npm test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    env:
      REACT_APP_MOVIE_API_URL: http://localhost:5000
    defaults:
      run:
        working-directory: ./starter/frontend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './starter/frontend/package-lock.json'
          
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ./starter/frontend/node_modules
            *!node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: CI=true npm test
        
      - name: Build application
        run: npm run build
        
      - name: Build Docker image
        run: docker build --build-arg=REACT_APP_MOVIE_API_URL=${{ env.REACT_APP_MOVIE_API_URL }} -t frontend-app . 